kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: adtya.xyz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: adtya-xyz
          image: ghcr.io/adtya/adtya.xyz:trunk
          resources:
            limits:
              memory: 100M
              cpu: 100m
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: adtya-xyz
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
